[tox]
envlist = py310, py311, py312, py313, py314
isolated_build = true

[testenv]
deps =
    pytest>=9.0.2
    pytest-cov>=7.1.0
    pytest-mock>=3.15.1
commands =
    pytest --capture=sys \
        --junit-xml=coverage/test-results-{envname}.xml \
        --cov=htmligator \
        --cov-report term-missing \
        --cov-report xml:coverage/coverage-{envname}.xml \
        --cov-report html:coverage/coverage-{envname} \
        --cov-report lcov:coverage/coverage-{envname}.info

